In [7]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt

In [17]:
df_drink = pd.read_csv('../data/menu_data.csv')
df_log = pd.read_csv('../data/order_data.csv')

In [ ]:
order_counts = df_log['음료명'].value_counts()
# df_log에 없는 음료 목록 df_drink에서 가져와서 리스트로 만들기
drink_list = df_drink['음료명'].tolist()
for drink in order_counts.index :
    if drink not in drink_list :
        order_counts.drop(drink, inplace=True)
top_5_orders = order_counts.head(5)
if len(drink_list) in [1, 2, 3, 4] :
    bottom_5_orders = order_counts.tail(5 - len(drink_list))
    list_to_add = [0] * len(drink_list)
    series_from_list = pd.Series(list_to_add, index=drink_list)
    bottom_5_orders = pd.concat([bottom_5_orders, series_from_list])
elif len(drink_list) == 0 :
    bottom_5_orders = order_counts.tail(5)
else :
    random_drinks = np.random.choice(drink_list, 5, replace=False)
    list_to_add = [0] * 5
    bottom_5_orders = pd.Series(list_to_add, index=random_drinks)

In [27]:
# drink_list를 시리즈로 변환하려면?
drink_series = pd.Series(drink_list)
drink_series

0          나이트로 바닐라 크림
1          나이트로 바닐라 크림
2          나이트로 바닐라 크림
3           나이트로 콜드 브루
4           나이트로 콜드 브루
            ...
231        한라봉주스 190ML
232       햇사과 주스 190ML
233       햇사과 주스 591ML
234    딸기 가득 요거트 190ML
235     블루베리 요거트 190ML
Length: 236, dtype: object

In [23]:
order_counts.index

Index(['오늘의 커피', '자바 칩 프라푸치노', '나이트로 콜드 브루', '아이스 커피', '헤이즐넛 클라우드 모카',
       '카페 아메리카노', '아이스 카푸치노', '초콜릿 크림 칩 프라푸치노', '에스프레소 프라푸치노',
       '딸기 아사이 레모네이드 스타벅스 리프레셔', '쿨 라임 피지오', '복숭아 아이스 티', '아이스 스타벅스 클래식 밀크 티',
       '유자 민트 티', '아이스 자몽 허니 블랙 티'],
      dtype='object', name='음료명')

In [25]:
top_5_orders.index

Index(['오늘의 커피', '자바 칩 프라푸치노', '나이트로 콜드 브루', '아이스 커피', '헤이즐넛 클라우드 모카'], dtype='object', name='음료명')

In [ ]:
drink_list

'나이트로 바닐라 크림'

In [31]:
bottom_5_orders

음료명
쿨 라임 피지오             1
복숭아 아이스 티            1
아이스 스타벅스 클래식 밀크 티    1
유자 민트 티              1
아이스 자몽 허니 블랙 티       1
Name: count, dtype: int64

In [2]:
df = pd.read_csv('../data/new_movie.csv')
df

,제목,제작 비용 ($),북미 박스오피스 수익 ($),전세계 박스오피스 수익 ($),개봉 주말 수익 ($),상영 등급,장르,상영관 수,상영 시간,개봉 연도,영화 유형
0,Avengers: Endgame,400000000,858373000.0,2.797801e+09,357115007.0,PG-13,Action,4662.0,181.0,2019,1
1,Pirates of the Caribbean: On Stranger Tides,379000000,241071802.0,1.045714e+09,90151958.0,PG-13,Adventure,4164.0,136.0,2011,1
2,Avengers: Age of Ultron,365000000,459005868.0,1.395317e+09,191271109.0,PG-13,Action,4276.0,141.0,2015,1
3,Star Wars Ep. VII: The Force Awakens,306000000,936662225.0,2.064616e+09,247966675.0,PG-13,Adventure,4134.0,136.0,2015,1
4,Avengers: Infinity War,300000000,678815482.0,2.048360e+09,257698183.0,PG-13,Action,4474.0,156.0,2018,1
...,...,...,...,...,...,...,...,...,...,...,...
486,The Incredibles,92000000,261441092.0,6.314411e+08,70467623.0,PG,Adventure,3933.0,115.0,2004,0
487,A Good Day to Die Hard,92000000,67349198.0,3.042492e+08,24834845.0,R,Action,3555.0,98.0,2013,0
488,The Alamo,92000000,22406362.0,2.391136e+07,9124701.0,PG-13,Western,2609.0,137.0,2004,0
489,Cutthroat Island,92000000,10017322.0,1.851732e+07,2371415.0,PG-13,Adventure,1619.0,122.0,1995,0
490,The Secret Life of Walter Mitty,91000000,58236838.0,1.878612e+08,12765508.0,PG,Adventure,2922.0,114.0,2013,0

In [3]:
df.describe()

,제작 비용 ($),북미 박스오피스 수익 ($),전세계 박스오피스 수익 ($),개봉 주말 수익 ($),상영관 수,상영 시간,개봉 연도,영화 유형
count,4.910000e+02,4.910000e+02,4.910000e+02,4.910000e+02,491.000000,491.000000,491.000000,491.000000
mean,1.494872e+08,1.753206e+08,4.779511e+08,5.429206e+07,3659.775967,121.865580,2011.358452,0.830957
std,4.759424e+07,1.394589e+08,3.830213e+08,4.562877e+07,539.291514,22.303341,6.533261,0.935654
min,9.100000e+07,3.114340e+05,7.561500e+04,4.855800e+04,30.000000,76.000000,1991.000000,0.000000
25%,1.100000e+08,7.872882e+07,2.186231e+08,2.467904e+07,3394.000000,105.000000,2007.000000,0.000000
50%,1.400000e+08,1.385409e+08,3.748258e+08,4.363974e+07,3711.000000,120.000000,2012.000000,0.000000
75%,1.750000e+08,2.191196e+08,6.484352e+08,6.770120e+07,4058.500000,135.000000,2016.000000,2.000000
max,4.000000e+08,9.366622e+08,2.910371e+09,3.571150e+08,4802.000000,210.000000,2022.000000,2.000000

In [4]:
X = df.loc[:, ['제작 비용 ($)', '개봉 주말 수익 ($)', '상영 등급', '장르', '상영 시간', '개봉 연도']]
X

     제작 비용 ($)  개봉 주말 수익 ($)  상영 등급         장르  상영 시간  개봉 연도
0    400000000   357115007.0  PG-13     Action  181.0   2019
1    379000000    90151958.0  PG-13  Adventure  136.0   2011
2    365000000   191271109.0  PG-13     Action  141.0   2015
3    306000000   247966675.0  PG-13  Adventure  136.0   2015
4    300000000   257698183.0  PG-13     Action  156.0   2018
..         ...           ...    ...        ...    ...    ...
486   92000000    70467623.0     PG  Adventure  115.0   2004
487   92000000    24834845.0      R     Action   98.0   2013
488   92000000     9124701.0  PG-13    Western  137.0   2004
489   92000000     2371415.0  PG-13  Adventure  122.0   1995
490   91000000    12765508.0     PG  Adventure  114.0   2013

[491 rows x 6 columns]

In [5]:
y = df.loc[:, '북미 박스오피스 수익 ($)'].to_frame()
y

     북미 박스오피스 수익 ($)
0        858373000.0
1        241071802.0
2        459005868.0
3        936662225.0
4        678815482.0
..               ...
486      261441092.0
487       67349198.0
488       22406362.0
489       10017322.0
490       58236838.0

[491 rows x 1 columns]

#### 인코딩

In [6]:
from sklearn.preprocessing import LabelEncoder
from pandas.api.types import is_integer_dtype, is_float_dtype, is_object_dtype

In [7]:
X_new = pd.DataFrame()

for col in X:
    if is_integer_dtype(X[col]) : 
        X_new[col] = X[col]
    elif is_float_dtype(X[col]) :
        X_new[col] = X[col]
    elif is_object_dtype(X[col]) :
        encoder = LabelEncoder()
        X_new[col] = encoder.fit_transform(X[col])

In [8]:
X_new

     제작 비용 ($)  개봉 주말 수익 ($)  상영 등급  장르  상영 시간  개봉 연도
0    400000000   357115007.0      2   0  181.0   2019
1    379000000    90151958.0      2   1  136.0   2011
2    365000000   191271109.0      2   0  141.0   2015
3    306000000   247966675.0      2   1  136.0   2015
4    300000000   257698183.0      2   0  156.0   2018
..         ...           ...    ...  ..    ...    ...
486   92000000    70467623.0      1   1  115.0   2004
487   92000000    24834845.0      3   0   98.0   2013
488   92000000     9124701.0      2   9  137.0   2004
489   92000000     2371415.0      2   1  122.0   1995
490   91000000    12765508.0      1   1  114.0   2013

[491 rows x 6 columns]

#### 데이터 분할

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size = 0.2, random_state = 4)

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [12]:
regressor1 = LinearRegression()
regressor2 = RandomForestRegressor(n_estimators=500, random_state=4)
regressor3 = XGBRegressor(n_estimators=500, random_state=4, learning_rate=0.5)

#### y 계산

In [13]:
regressor1.fit(X_train, y_train)
regressor2.fit(X_train, y_train)
regressor3.fit(X_train, y_train)

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.5, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=500, n_jobs=None,
             num_parallel_tree=None, random_state=4, ...)

In [14]:
y_pred1 = regressor1.predict(X_test)
y_pred2 = regressor2.predict(X_test)
y_pred3 = regressor3.predict(X_test)

In [15]:
from sklearn.metrics import mean_squared_error, r2_score

In [16]:
mean_squared_error(y_test, y_pred1)

5647090910646960.0

In [17]:
r2_score(y_test, y_pred1)

0.7300405135072934

In [18]:
mean_squared_error(y_test, y_pred2)

7030676884900312.0

In [19]:
r2_score(y_test, y_pred2)

0.6638981111557163

In [20]:
mean_squared_error(y_test, y_pred3)

7143401281205397.0

In [21]:
r2_score(y_test, y_pred3)

0.658509373664856

In [22]:
df_y = pd.DataFrame(y_test)

In [23]:
df_y['y_pred'] = y_pred1

In [24]:
df_y

     북미 박스오피스 수익 ($)        y_pred
299     3.371359e+08  3.726999e+08
265     1.269307e+08  1.355979e+08
446     2.878248e+07  3.676361e+07
11      3.303602e+08  4.764893e+08
162     1.031443e+08  1.223740e+08
..               ...           ...
377     6.618405e+07  9.109289e+07
153     7.704238e+07  1.078499e+08
314     1.132039e+08  1.555352e+08
341     1.696114e+08  1.311005e+08
368     1.065801e+08  1.034057e+08

[99 rows x 2 columns]

In [25]:
X_new

     제작 비용 ($)  개봉 주말 수익 ($)  상영 등급  장르  상영 시간  개봉 연도
0    400000000   357115007.0      2   0  181.0   2019
1    379000000    90151958.0      2   1  136.0   2011
2    365000000   191271109.0      2   0  141.0   2015
3    306000000   247966675.0      2   1  136.0   2015
4    300000000   257698183.0      2   0  156.0   2018
..         ...           ...    ...  ..    ...    ...
486   92000000    70467623.0      1   1  115.0   2004
487   92000000    24834845.0      3   0   98.0   2013
488   92000000     9124701.0      2   9  137.0   2004
489   92000000     2371415.0      2   1  122.0   1995
490   91000000    12765508.0      1   1  114.0   2013

[491 rows x 6 columns]

#### 신규 데이터 예측

In [26]:
new_data = np.array([170000000, 80000000, 3, 7, 143, 2025]).reshape(1, 6)
new_data

array([[170000000,  80000000,         3,         7,       143,      2025]])

In [27]:
regressor1.predict(new_data)[0]
import joblib

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [28]:
joblib.dump(regressor1, '../model/regressor.pkl')

['../model/regressor.pkl']